# Spingere l'uso di ZRAM in caso di pressione memoria
vm.swappiness=100
# Tenere in cache dentry/inode più a lungo
vm.vfs_cache_pressure=50
# Scrivere dirty pages più spesso per evitare blocchi I/O
vm.dirty_ratio=15
vm.dirty_background_ratio=5
# Disabilita NMI watchdog (meno interruzioni CPU)
kernel.nmi_watchdog=0
# Riduce l'overhead di memory compaction
vm.compaction_proactiveness=0
