[Interface]
PrivateKey = mI8oRj2OERLK2a8YXcLdAFFEng19P3hX9NFklFAsi1M=
Address = 10.10.10.97/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = U+rvrtBL1INm/UQzAZzJ/wxjrmEeUwqfK5Rj+6mP4V4=
PresharedKey = AE3v57cUn5t6BavDw+WXjGNFlmwQ4Jm+YUijR1oLUF8=
Endpoint = vpn.teleufficio.it:51820
AllowedIPs = 10.10.10.0/24
PersistentKeepalive = 25
